language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio

script:
    - platformio ci --lib="." --project-conf platformio.ci.ini --exclude=lib/aquarium_lights/src/debug/\* --exclude=lib/aquarium_lights/src/main.cpp   --keep-build-dir   --lib="test_lib/unity"  test
